version: '3'

services:
  traefik:
    container_name: traefik
    restart: always
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

networks:
  web:
    name: web